Add different LFO deform types
surge-synthesizer/surge pull request #3005
Opened 2020-10-29 22:30 UTC by VincyZed

- Added different LFO deform types (right-click on Deform, Type 1, Type 2 or Type 3).

I made those formulas based on the feedback on the LFO Display, so it could be possible that it might go slightly (and I mean very slightly, if it's the case) out of bounds.

I tested saving and loading patches (including backwards compatibility) and streaming works.

2020-10-29 23:27 UTC, mkruselj requested changes

2020-10-30 12:38 UTC, baconpaul commented
I agree with @mkruselj suggestion but otherwise think the change is great and would merge once you do that small update. Thank you!

2020-10-30 12:50 UTC, VincyZed commented
Sounds good, will work on that today. Thanks guys!

2020-10-30 19:54 UTC, merged

2020-10-30 19:55 UTC, baconpaul commented
Merged! Thanks!

2020-10-30 20:02 UTC, mkruselj approved these changes